services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CoinTracker
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:8.2.1-alpine
    container_name: redis
    restart: always
    environment:
      REDIS_PORT: 6379
      REDIS_DB: 0
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  bot:
    build: .
    container_name: bot
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  redisdata:
  pgdata: